### ISSUE TITLE
about paf2maf

### ISSUE THREAD

**Issue by 790634750** [atongsa/atongsa.github.io#1]
Hello, I see that you asked a question about paf2maf under paftools before. The paf format can only be the paf generated by minimap2. Other paf formats cannot be converted into maf by this software. I'm stuck with this problem now, have you made any progress on solving it? Thank you very much for your reply

**Comment by atongsa** [comment]
1) i just use paftools paf2maf to convert paf to maf as described by lh3 in that issues;

2) actually, i don't know the diff of paf formats that generated by diffent software, and  that 'Other paf formats cannot be converted into maf by this software';

3) sorry for can't offer help
